### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by reedniv** [aoii103/AntiCloudFare#4]
I have problem with error like this 

`.../bypass/AntiCloudFlare $ python crack.py --url https://google.com
[2021-05-10 18:07:34,786]<RequestsCookieJar[<Cookie 1P_JAR=2021-05-10-11 for .google.com/>, <Cookie NID=215=R-gPH6M8QFAI24RtndRyXvlBcryvbL-ko-WsyKqVJS3BSfQrliqebVtoGj5Dwjs-IqRCL1ox-uV4MEl__fxE6EXthbaYjZ95GeOp58eAyY9AoMyaQRhuR699VlWK8czsmN7xaWmGIY-IHSMkHY0IVuAme2CMEBmq3i01a_ak9Ec for .google.com/>]>
[2021-05-10 18:07:34,793]url: https://www.google.com/
[2021-05-10 18:07:34,793]content: 35674
Traceback (most recent call last):
  File "crack.py", line 153, in <module>
    test()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "crack.py", line 133, in test
    Crack(resp.text, resp.url, end_time, save_res=True),
  File "crack.py", line 43, in Crack
    jq(content)("script")
IndexError: list index out of range`

**Comment by reedniv** [comment]
#3
